version: '2'
services:
  influxdb:
    image: influxdb:latest
    network_mode: host
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=Aa123456
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=asdnlsf349085j23nldknv
  chronograf:
    image: quay.io/influxdb/chronograf:1.8.10
    network_mode: host
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://127.0.0.1:8086
      - INFLUXDB_USERNAME=test
      - INFLUXDB_PASSWORD=Aa123456
  grafana:
    image: grafana/grafana:latest
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage: